- name: install epel
  yum: name=epel-release state=latest

- name: install git
  yum: name=git state=latest

- name: install vim
  yum: name=vim state=latest

- name: install prerequisites for ansible module
  yum: name=libselinux-python state=latest

- name: install prerequisites for ruby
  yum: name={{ item }} state=latest
  with_items: "{{prerequisites}}"

