<%
  dev_database  = 'property_db'
  test_database = 'property_db_test'
  user_name     = 'property_admin'
  password      = 'password'
%>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= user_name %>
  password: <%= password %>
  host: localhost

development:
  <<: *default
  database: <%= dev_database %>

test:
  <<: *default
  database: <%= test_database %>

production:
  <<: *default
  database: <%= dev_database %>
  username: <%= user_name %>
  password: <%= password %>